### ISSUE TITLE
No module named 'six'

### ISSUE THREAD

**Issue by softouch1** [FinixLei/WeChat_LandLords#1]
C:\Python36\python.exe E:/python_projects/WeChat_LandLords-master/solve_puzzle.py
Traceback (most recent call last):
  File "E:/python_projects/WeChat_LandLords-master/solve_puzzle.py", line 4, in <module>
    from ui_engine import UIEngine
  File "E:\python_projects\WeChat_LandLords-master\ui_engine.py", line 6, in <module>
    from six.moves import input
ModuleNotFoundError: No module named 'six'
为嘛会提示这个？

**Comment by softouch1** [comment]
> C:\Python36\python.exe E:/python_projects/WeChat_LandLords-master/solve_puzzle.py
> Traceback (most recent call last):
> File "E:/python_projects/WeChat_LandLords-master/solve_puzzle.py", line 4, in 
> from ui_engine import UIEngine
> File "E:\python_projects\WeChat_LandLords-master\ui_engine.py", line 6, in 
> from six.moves import input
> ModuleNotFoundError: No module named 'six'
> 为嘛会提示这个？

我懒了，注释掉就好了

**Comment by FinixLei** [comment]
你没有安装six模块

**Comment by FinixLei** [comment]
Need to install "six" module.
