### ISSUE TITLE
start_engine函数的问题

### ISSUE THREAD

**Issue by okman334** [FinixLei/WeChat_LandLords#3]
MinMax.hpp的start_engine的参数current_player并没有被使用，而多线程版本和单线程版本调用min_max_search的时候，传入的current_player刚好相反，多线程传的FARMER，单线程传的LORDER？求解答一下，谢谢：）

**Comment by FinixLei** [comment]
确实要传入相反啊。单线程是从头算起；多线程是每个线程已经得到了第一步打法，所以是从第二步算起，自然出牌人就相反了啊。

**Comment by okman334** [comment]
我能不能理解为start_engine只是针对LORDER出牌做了计算，对FARMER出牌的情况没有写？

**Comment by FinixLei** [comment]
> 我能不能理解为start_engine只是针对LORDER出牌做了计算，对FARMER出牌的情况没有写？

没错。这个函数本意是尽可能general的，可以对Lorder计算，也可以对Farmer计算。但在这个程序中，只会针对Lorder计算。所以，就本程序而言，也确实可以把它的最后一个参数去掉。不过，考虑到扩展性，还是加上了。

**Comment by okman334** [comment]
好的. 谢谢回复～

**Comment by okman334** [comment]
> > 我能不能理解为start_engine只是针对LORDER出牌做了计算，对FARMER出牌的情况没有写？
> 
> 没错。这个函数本意是尽可能general的，可以对Lorder计算，也可以对Farmer计算。但在这个程序中，只会针对Lorder计算。所以，就本程序而言，也确实可以把它的最后一个参数去掉。不过，考虑到扩展性，还是加上了。

我想根据你这个项目改造一个残局机器人出牌逻辑：）但我发现start_engine返回MIN_SCORE的时候，就不带出牌数据了。

**Comment by FinixLei** [comment]
> > > 我能不能理解为start_engine只是针对LORDER出牌做了计算，对FARMER出牌的情况没有写？
> > 
> > 
> > 没错。这个函数本意是尽可能general的，可以对Lorder计算，也可以对Farmer计算。但在这个程序中，只会针对Lorder计算。所以，就本程序而言，也确实可以把它的最后一个参数去掉。不过，考虑到扩展性，还是加上了。
> 
> 我想根据你这个项目改造一个残局机器人出牌逻辑：）但我发现start_engine返回MIN_SCORE的时候，就不带出牌数据了。

自己改改吧。这里要理解最大最小值算法，然后估计才能应用到自己的程序中。祝玩得愉快。

**Comment by FinixLei** [comment]
主要是应用min_max_search

**Comment by okman334** [comment]
好的，我好好读读源码：）

Lei Lei <notifications@github.com>于2019年12月17日 周二下午8:17写道：
